// Code generated by ent, DO NOT EDIT.

package ent

import (
	"metrograma/ent/schema"
	"metrograma/ent/subject"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	subjectFields := schema.Subject{}.Fields()
	_ = subjectFields
	// subjectDescSubjectName is the schema descriptor for subject_name field.
	subjectDescSubjectName := subjectFields[2].Descriptor()
	// subject.SubjectNameValidator is a validator for the "subject_name" field. It is called by the builders before save.
	subject.SubjectNameValidator = subjectDescSubjectName.Validators[0].(func(string) error)
	// subjectDescSubjectCode is the schema descriptor for subject_code field.
	subjectDescSubjectCode := subjectFields[3].Descriptor()
	// subject.SubjectCodeValidator is a validator for the "subject_code" field. It is called by the builders before save.
	subject.SubjectCodeValidator = subjectDescSubjectCode.Validators[0].(func(string) error)
	// subjectDescCareerName is the schema descriptor for career_name field.
	subjectDescCareerName := subjectFields[4].Descriptor()
	// subject.CareerNameValidator is a validator for the "career_name" field. It is called by the builders before save.
	subject.CareerNameValidator = subjectDescCareerName.Validators[0].(func(string) error)
}
