/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as NavLayoutRouteRouteImport } from './routes/_navLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterStudentRouteImport } from './routes/register/student'
import { Route as NavLayoutProfileRouteRouteImport } from './routes/_navLayout/profile/route'
import { Route as NavLayoutProfileIndexRouteImport } from './routes/_navLayout/profile/index'
import { Route as NavLayoutOfertaIndexRouteImport } from './routes/_navLayout/oferta/index'
import { Route as NavLayoutMateriasIndexRouteImport } from './routes/_navLayout/materias/index'
import { Route as NavLayoutHorarioIndexRouteImport } from './routes/_navLayout/horario/index'
import { Route as AdminCarrerasCrearRouteImport } from './routes/admin/carreras.crear'
import { Route as NavLayoutStudentStudentIdRouteImport } from './routes/_navLayout/student/$studentId'
import { Route as NavLayoutOfertaEditRouteImport } from './routes/_navLayout/oferta/edit'
import { Route as NavLayoutProfileSettingsIndexRouteImport } from './routes/_navLayout/profile/settings/index'
import { Route as AdminCarrerasEditarIdRouteImport } from './routes/admin/carreras.editar.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NavLayoutRouteRoute = NavLayoutRouteRouteImport.update({
  id: '/_navLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const NavLayoutProfileRouteRoute = NavLayoutProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NavLayoutRouteRoute,
} as any)
const NavLayoutProfileIndexRoute = NavLayoutProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavLayoutProfileRouteRoute,
} as any)
const NavLayoutOfertaIndexRoute = NavLayoutOfertaIndexRouteImport.update({
  id: '/oferta/',
  path: '/oferta/',
  getParentRoute: () => NavLayoutRouteRoute,
} as any)
const NavLayoutMateriasIndexRoute = NavLayoutMateriasIndexRouteImport.update({
  id: '/materias/',
  path: '/materias/',
  getParentRoute: () => NavLayoutRouteRoute,
} as any)
const NavLayoutHorarioIndexRoute = NavLayoutHorarioIndexRouteImport.update({
  id: '/horario/',
  path: '/horario/',
  getParentRoute: () => NavLayoutRouteRoute,
} as any)
const AdminCarrerasCrearRoute = AdminCarrerasCrearRouteImport.update({
  id: '/carreras/crear',
  path: '/carreras/crear',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NavLayoutStudentStudentIdRoute =
  NavLayoutStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => NavLayoutRouteRoute,
  } as any)
const NavLayoutOfertaEditRoute = NavLayoutOfertaEditRouteImport.update({
  id: '/oferta/edit',
  path: '/oferta/edit',
  getParentRoute: () => NavLayoutRouteRoute,
} as any)
const NavLayoutProfileSettingsIndexRoute =
  NavLayoutProfileSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => NavLayoutProfileRouteRoute,
  } as any)
const AdminCarrerasEditarIdRoute = AdminCarrerasEditarIdRouteImport.update({
  id: '/carreras/editar/$id',
  path: '/carreras/editar/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/profile': typeof NavLayoutProfileRouteRouteWithChildren
  '/register/student': typeof RegisterStudentRoute
  '/oferta/edit': typeof NavLayoutOfertaEditRoute
  '/student/$studentId': typeof NavLayoutStudentStudentIdRoute
  '/admin/carreras/crear': typeof AdminCarrerasCrearRoute
  '/horario/': typeof NavLayoutHorarioIndexRoute
  '/materias/': typeof NavLayoutMateriasIndexRoute
  '/oferta/': typeof NavLayoutOfertaIndexRoute
  '/profile/': typeof NavLayoutProfileIndexRoute
  '/admin/carreras/editar/$id': typeof AdminCarrerasEditarIdRoute
  '/profile/settings/': typeof NavLayoutProfileSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/register/student': typeof RegisterStudentRoute
  '/oferta/edit': typeof NavLayoutOfertaEditRoute
  '/student/$studentId': typeof NavLayoutStudentStudentIdRoute
  '/admin/carreras/crear': typeof AdminCarrerasCrearRoute
  '/horario': typeof NavLayoutHorarioIndexRoute
  '/materias': typeof NavLayoutMateriasIndexRoute
  '/oferta': typeof NavLayoutOfertaIndexRoute
  '/profile': typeof NavLayoutProfileIndexRoute
  '/admin/carreras/editar/$id': typeof AdminCarrerasEditarIdRoute
  '/profile/settings': typeof NavLayoutProfileSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_navLayout': typeof NavLayoutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_navLayout/profile': typeof NavLayoutProfileRouteRouteWithChildren
  '/register/student': typeof RegisterStudentRoute
  '/_navLayout/oferta/edit': typeof NavLayoutOfertaEditRoute
  '/_navLayout/student/$studentId': typeof NavLayoutStudentStudentIdRoute
  '/admin/carreras/crear': typeof AdminCarrerasCrearRoute
  '/_navLayout/horario/': typeof NavLayoutHorarioIndexRoute
  '/_navLayout/materias/': typeof NavLayoutMateriasIndexRoute
  '/_navLayout/oferta/': typeof NavLayoutOfertaIndexRoute
  '/_navLayout/profile/': typeof NavLayoutProfileIndexRoute
  '/admin/carreras/editar/$id': typeof AdminCarrerasEditarIdRoute
  '/_navLayout/profile/settings/': typeof NavLayoutProfileSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/register/student'
    | '/oferta/edit'
    | '/student/$studentId'
    | '/admin/carreras/crear'
    | '/horario/'
    | '/materias/'
    | '/oferta/'
    | '/profile/'
    | '/admin/carreras/editar/$id'
    | '/profile/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/register/student'
    | '/oferta/edit'
    | '/student/$studentId'
    | '/admin/carreras/crear'
    | '/horario'
    | '/materias'
    | '/oferta'
    | '/profile'
    | '/admin/carreras/editar/$id'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/_navLayout'
    | '/admin'
    | '/_navLayout/profile'
    | '/register/student'
    | '/_navLayout/oferta/edit'
    | '/_navLayout/student/$studentId'
    | '/admin/carreras/crear'
    | '/_navLayout/horario/'
    | '/_navLayout/materias/'
    | '/_navLayout/oferta/'
    | '/_navLayout/profile/'
    | '/admin/carreras/editar/$id'
    | '/_navLayout/profile/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NavLayoutRouteRoute: typeof NavLayoutRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  RegisterStudentRoute: typeof RegisterStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navLayout': {
      id: '/_navLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navLayout/profile': {
      id: '/_navLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof NavLayoutProfileRouteRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/_navLayout/profile/': {
      id: '/_navLayout/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof NavLayoutProfileIndexRouteImport
      parentRoute: typeof NavLayoutProfileRouteRoute
    }
    '/_navLayout/oferta/': {
      id: '/_navLayout/oferta/'
      path: '/oferta'
      fullPath: '/oferta/'
      preLoaderRoute: typeof NavLayoutOfertaIndexRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/_navLayout/materias/': {
      id: '/_navLayout/materias/'
      path: '/materias'
      fullPath: '/materias/'
      preLoaderRoute: typeof NavLayoutMateriasIndexRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/_navLayout/horario/': {
      id: '/_navLayout/horario/'
      path: '/horario'
      fullPath: '/horario/'
      preLoaderRoute: typeof NavLayoutHorarioIndexRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/admin/carreras/crear': {
      id: '/admin/carreras/crear'
      path: '/carreras/crear'
      fullPath: '/admin/carreras/crear'
      preLoaderRoute: typeof AdminCarrerasCrearRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_navLayout/student/$studentId': {
      id: '/_navLayout/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof NavLayoutStudentStudentIdRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/_navLayout/oferta/edit': {
      id: '/_navLayout/oferta/edit'
      path: '/oferta/edit'
      fullPath: '/oferta/edit'
      preLoaderRoute: typeof NavLayoutOfertaEditRouteImport
      parentRoute: typeof NavLayoutRouteRoute
    }
    '/_navLayout/profile/settings/': {
      id: '/_navLayout/profile/settings/'
      path: '/settings'
      fullPath: '/profile/settings/'
      preLoaderRoute: typeof NavLayoutProfileSettingsIndexRouteImport
      parentRoute: typeof NavLayoutProfileRouteRoute
    }
    '/admin/carreras/editar/$id': {
      id: '/admin/carreras/editar/$id'
      path: '/carreras/editar/$id'
      fullPath: '/admin/carreras/editar/$id'
      preLoaderRoute: typeof AdminCarrerasEditarIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface NavLayoutProfileRouteRouteChildren {
  NavLayoutProfileIndexRoute: typeof NavLayoutProfileIndexRoute
  NavLayoutProfileSettingsIndexRoute: typeof NavLayoutProfileSettingsIndexRoute
}

const NavLayoutProfileRouteRouteChildren: NavLayoutProfileRouteRouteChildren = {
  NavLayoutProfileIndexRoute: NavLayoutProfileIndexRoute,
  NavLayoutProfileSettingsIndexRoute: NavLayoutProfileSettingsIndexRoute,
}

const NavLayoutProfileRouteRouteWithChildren =
  NavLayoutProfileRouteRoute._addFileChildren(
    NavLayoutProfileRouteRouteChildren,
  )

interface NavLayoutRouteRouteChildren {
  NavLayoutProfileRouteRoute: typeof NavLayoutProfileRouteRouteWithChildren
  NavLayoutOfertaEditRoute: typeof NavLayoutOfertaEditRoute
  NavLayoutStudentStudentIdRoute: typeof NavLayoutStudentStudentIdRoute
  NavLayoutHorarioIndexRoute: typeof NavLayoutHorarioIndexRoute
  NavLayoutMateriasIndexRoute: typeof NavLayoutMateriasIndexRoute
  NavLayoutOfertaIndexRoute: typeof NavLayoutOfertaIndexRoute
}

const NavLayoutRouteRouteChildren: NavLayoutRouteRouteChildren = {
  NavLayoutProfileRouteRoute: NavLayoutProfileRouteRouteWithChildren,
  NavLayoutOfertaEditRoute: NavLayoutOfertaEditRoute,
  NavLayoutStudentStudentIdRoute: NavLayoutStudentStudentIdRoute,
  NavLayoutHorarioIndexRoute: NavLayoutHorarioIndexRoute,
  NavLayoutMateriasIndexRoute: NavLayoutMateriasIndexRoute,
  NavLayoutOfertaIndexRoute: NavLayoutOfertaIndexRoute,
}

const NavLayoutRouteRouteWithChildren = NavLayoutRouteRoute._addFileChildren(
  NavLayoutRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCarrerasCrearRoute: typeof AdminCarrerasCrearRoute
  AdminCarrerasEditarIdRoute: typeof AdminCarrerasEditarIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCarrerasCrearRoute: AdminCarrerasCrearRoute,
  AdminCarrerasEditarIdRoute: AdminCarrerasEditarIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NavLayoutRouteRoute: NavLayoutRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  RegisterStudentRoute: RegisterStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
