// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Career is the predicate function for career builders.
type Career func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)
