// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SubjectsColumns holds the columns for the "subjects" table.
	SubjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "subject_name", Type: field.TypeString},
		{Name: "subject_code", Type: field.TypeString, Unique: true},
		{Name: "career_name", Type: field.TypeString},
		{Name: "trimester", Type: field.TypeUint8},
		{Name: "precedes_subject_id", Type: field.TypeUUID, Nullable: true},
	}
	// SubjectsTable holds the schema information for the "subjects" table.
	SubjectsTable = &schema.Table{
		Name:       "subjects",
		Columns:    SubjectsColumns,
		PrimaryKey: []*schema.Column{SubjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subjects_subjects_next_subject",
				Columns:    []*schema.Column{SubjectsColumns[5]},
				RefColumns: []*schema.Column{SubjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SubjectsTable,
	}
)

func init() {
	SubjectsTable.ForeignKeys[0].RefTable = SubjectsTable
}
